packaging_format = 2

id = "seaweedfs"
name = "SeaweedFS"
description.en = "Versatile and efficient storage system"
description.fr = "Système de stockage polyvalent et efficace"

version = "4.15~ynh1"

maintainers = ["otm33GH"]

[upstream]
license = "Apache-2.0"
website = "https://seaweedfs.com/"
userdoc = "https://github.com/seaweedfs/seaweedfs/wiki"
code = "https://github.com/seaweedfs/seaweedfs"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ['amd64', 'arm64']
multi_instance = false

ldap = false
sso = false

disk = "200M"
ram.build = "200M"
ram.runtime = "200M"

[install]

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"
    
    [install.admin_pw]
    ask.en = "Please chose a password for the admin user."
    ask.fr = "Choisissez un mot de passe pour l'administrateur."
    type = "password"
    
    [install.volume_size]
    ask.en = "Size of each volume in Mb"
    ask.fr = "Taille de chaque volume en Mo"
    help.en = "Will depend on free disk space. Each bucket will create one collection, with at least 7 volumes by default. Note that multiple volume servers can be created."
    help.fr = "En fonction de l'espace disque disponible. Cahque bucket crée une collection de, par défaut, 7 volumes. Plusieurs serveurs de volumes peuvent être créés ultérieurement."
    type = "number"
    default = 100
    min = 10
    max = 50000
       
[resources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/seaweedfs/seaweedfs/releases/download/4.15/linux_amd64.tar.gz"
    amd64.sha256 = "b7d401d247ccfec60ab6301e691d395310685be9cc3c4224f0765602793b2af4"
    arm64.url = "https://github.com/seaweedfs/seaweedfs/releases/download/4.15/linux_arm64.tar.gz"
    arm64.sha256 = "f01592ff4c0e2c2318ddcf6b77850754eb1408e44daf552fc337b03d4fda9b6f"

    autoupdate.asset.amd64 = "linux_amd64.tar.gz"
    autoupdate.asset.arm64 = "linux_arm64.tar.gz"
    autoupdate.strategy = "latest_github_release"
   
    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["datadir"]

    [resources.permissions]
    main.url = "/"
    admin.url = "/admin"
    admin.allowed = "admins"
    admin.auth_header = false
    
    [resources.ports]
    admin.default = 23646
    master.default = 9333
    filer.default = 8888
    volume.default = 8080
    api.default = 8333 # port pour s3
