#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;

location ~ ^/(admin|api|cluster|mq|object-store|metrics|files|plugin|logs|storage|maintenance|login)($|/){
        include proxy_params_no_auth;
        proxy_pass http://127.0.0.1:__PORT_ADMIN__;
        proxy_redirect    off;
        client_max_body_size  __UPLOAD_MAX_SIZE__M;
    }

location /static/ {
        include proxy_params_no_auth;
        proxy_pass http://127.0.0.1:__PORT_ADMIN__;
        proxy_redirect    off;
    }

location = / {
    default_type text/plain;
    return 200 "SeaweedFS S3 endpoint\n";
}

location / {
        include proxy_params_no_auth;
        proxy_pass http://127.0.0.1:__PORT_API__/;
        proxy_redirect    off;
        client_max_body_size  __UPLOAD_MAX_SIZE__M;
        more_set_headers "Content-Security-Policy: frame-ancestors 'self' __ALLOWED_URLS__";
    }
