#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================


for index_worker in "${worker_index[@]}"; do
    ynh_systemctl --service="$app-worker@${index_worker}" --action="stop" --log_path="systemd"
    sleep 5
    yunohost service remove "$app-worker@${index_worker}"
    ynh_safe_rm /etc/systemd/system/$app-worker@${index_worker}.service
    ynh_app_setting_delete --key="${app}-worker@${index_worker}" 2>/dev/null || true
    ynh_app_setting_delete --key=checksum__etc_systemd_system_$app-worker@${index_worker}.service
    pushd "$install_dir"
        ynh_safe_rm worker@${index_worker}.id
    popd
done

ynh_backup "$install_dir"

#=================================================
# BACKUP THE DATA DIR
#=================================================

ynh_backup "$data_dir"

#=================================================
# BACKUP SYSTEM CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_backup "/etc/systemd/system/$app-master.service"
ynh_backup "/etc/systemd/system/$app-filer.service"

for index_volume in "${volume_index[@]}"; do
	ynh_backup "/etc/systemd/system/$app-volume@$index_volume.service"
done

ynh_backup "/etc/systemd/system/$app-admin.service"
ynh_backup "/etc/systemd/system/$app-s3.service"

ynh_backup "/etc/logrotate.d/$app"

#=================================================
# RECREATE DEFAULT WORKER
#=================================================
next_index=1
  ynh_config_add_systemd --service="$app-worker@$next_index" --template="worker.service"
  yunohost service add "$app-worker@$next_index" --description="SeaweedFS worker@$next_index" --log="/var/log/$app/$app-worker@${next_index}.log"
  ynh_systemctl --service="$app-worker@$next_index" --action="start"

### change worker id
  pushd "$install_dir"
    sleep 5
# add check
    if [ -f worker.id ]; then
        mv worker.id "worker@${next_index}.id"
    fi
  popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
