#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE SETTINGS
#=================================================

upload_max_size=500
next_index=1

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_config_add_systemd --service="$app-master" --template="master.service"
ynh_config_add_systemd --service="$app-volume@$next_index" --template="volume.service"
ynh_config_add_systemd --service="$app-filer" --template="filer.service"
ynh_config_add_systemd --service="$app-s3" --template="s3.service"
ynh_config_add_systemd --service="$app-worker@$next_index" --template="worker.service"
ynh_config_add_systemd --service="$app-admin" --template="admin.service"

ynh_app_setting_set --app=$app --key=upload_max_size --value=$upload_max_size

yunohost service add "$app-master" --description="SeaweedFS Master" --log="/var/log/$app/$app-master.log"
yunohost service add "$app-volume@$next_index" --description="SeaweedFS volume@$next_index" --log="/var/log/$app/$app-volume@${next_index}.log"
yunohost service add "$app-filer" --description="SeaweedFS Filer" --log="/var/log/$app/$app-filer.log"
yunohost service add "$app-s3" --description="SeaweedFS S3 API" --log="/var/log/$app/$app-s3.log"
yunohost service add "$app-worker@$next_index" --description="SeaweedFS worker@$next_index" --log="/var/log/$app/$app-worker@${next_index}.log"
yunohost service add "$app-admin" --description="SeaweedFS Admin UI" --log="/var/log/$app/$app-admin.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-master" --action="start"
ynh_systemctl --service="$app-volume@$next_index" --action="start"
ynh_systemctl --service="$app-filer" --action="start"
ynh_systemctl --service="$app-s3" --action="start"
ynh_systemctl --service="$app-worker@$next_index" --action="start"
ynh_systemctl --service="$app-admin" --action="start"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

# Create a dedicated Fail2Ban config
# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# NGINX CONFIGURATION
#=================================================

ynh_config_add_nginx

ynh_systemctl --service=nginx --action=reload

sleep 10

pushd "$install_dir"
	mv worker.id "worker@${next_index}.id"
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
