#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# ynh_config_remove_fail2ban

ynh_config_remove_logrotate

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
ynh_script_progression "Removing system configurations related to $app..."

ynh_systemctl --service="$app-filer" --action="stop" --log_path="systemd"
ynh_systemctl --service="$app-master" --action="stop" --log_path="systemd"
ynh_systemctl --service="$app-admin" --action="stop" --log_path="systemd"


ynh_systemctl --service="$app-volume" --action="stop" --log_path="systemd"
yunohost service remove "$app-volume"

ynh_systemctl --service="$app-worker" --action="stop" --log_path="systemd"

ynh_systemctl --service="$app-s3" --action="stop" --log_path="systemd"

if ynh_hide_warnings yunohost service status "$app-filer" >/dev/null; then
    yunohost service remove "$app-filer"
fi
ynh_config_remove_systemd "$app-filer"

if ynh_hide_warnings yunohost service status "$app-master" >/dev/null; then
    yunohost service remove "$app-master"
fi
ynh_config_remove_systemd "$app-master"

if ynh_hide_warnings yunohost service status "$app-admin" >/dev/null; then
    yunohost service remove "$app-admin"
fi
ynh_config_remove_systemd "$app-admin"

if ynh_hide_warnings yunohost service status "$app-s3" >/dev/null; then
    yunohost service remove "$app-s3"
fi
ynh_config_remove_systemd "$app-s3"

ynh_config_remove_nginx
ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
