#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

next_index=1

chown -R "$app:$app" "$data_dir"
#=================================================
# RESTORE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Restoring nginx configuration related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_script_progression "Restoring $app's services..."


#### a. master
  ynh_restore "/etc/systemd/system/$app-master.service"
  systemctl enable "$app-master.service" --quiet
  yunohost service add "$app-master" --description="SeaweedFS Master" --log="/var/log/$app/$app-master.log"

#### b. volumes
  for index_volume in "${volume_index[@]}"; do
    ynh_restore "/etc/systemd/system/$app-volume@$index_volume.service"
    systemctl enable "$app-volume@$index_volume.service" --quiet
    yunohost service add "$app-volume@$index_volume" --description="SeaweedFS volume@$index_volume" --log="/var/log/$app/$app-volume@$index_volume.log"
  done

#### c. filer
  ynh_restore "/etc/systemd/system/$app-filer.service"
  systemctl enable "$app-filer.service" --quiet
  yunohost service add "$app-filer" --description="SeaweedFS Filer" --log="/var/log/$app/$app-filer.log"

#### d. s3 API
  ynh_restore "/etc/systemd/system/$app-s3.service"
  systemctl enable "$app-s3.service" --quiet
  yunohost service add "$app-s3" --description="SeaweedFS S3 API" --log="/var/log/$app/$app-s3.log"

#### e. recreate default worker

  ynh_config_add_systemd --service="$app-worker@$next_index" --template="worker.service"
  yunohost service add "$app-worker@$next_index" --description="SeaweedFS worker@$next_index" --log="/var/log/$app/$app-worker@${next_index}.log"
  yunohost service add "$app-admin" --description="SeaweedFS Admin UI" --log="/var/log/$app/$app-admin.log"

#### f. admin
  ynh_restore "/etc/systemd/system/$app-admin.service"
  systemctl enable "$app-admin.service" --quiet

mkdir -p "/var/log/"$app""
ynh_restore "/etc/logrotate.d/$app"
touch /var/log/$app/$app.log
chown -R $app:$app /var/log/$app/

#=================================================
# RELOAD NGINX AND THE APP SERVICES
#=================================================
ynh_script_progression "Reloading $app's services and NGINX web server..."

ynh_systemctl --service="$app-master" --action="start"

for index_volume in "${volume_index[@]}"; do
  ynh_systemctl --service="$app-volume@$index_volume" --action="start"
done

ynh_systemctl --service="$app-filer" --action="start"
ynh_systemctl --service="$app-s3" --action="start"

ynh_systemctl --service="$app-worker@$next_index" --action="start"

ynh_systemctl --service="$app-admin" --action="start"

ynh_systemctl --service=nginx --action=reload
pushd "$install_dir"
sleep 5
mv worker.id worker@${next_index}.id
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
