#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE SETTINGS
#=================================================

next_index=1

## upgrade from 4.13
jwt_signing=$(ynh_app_setting_get --app=$app --key=jwt_signing)
if [ -z "$jwt_signing" ]; then
    jwt_signing=$(ynh_string_random --length=32)
    ynh_app_setting_set --app=$app --key=jwt_signing --value=$jwt_signing
fi

jwt_filer_signing=$(ynh_app_setting_get --app=$app --key=jwt_filer_signing)
if [ -z "$jwt_filer_signing" ]; then
    jwt_filer_signing=$(ynh_string_random --length=32)
    ynh_app_setting_set --app=$app --key=jwt_filer_signing --value=$jwt_filer_signing
fi

jwt_filer_signing_read=$(ynh_app_setting_get --app=$app --key=jwt_filer_signing_read)
if [ -z "$jwt_filer_signing_read" ]; then
    jwt_filer_signing_read=$(ynh_string_random --length=32)
    ynh_app_setting_set --app=$app --key=jwt_filer_signing_read --value=$jwt_filer_signing_read
fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app-master" --action="stop" --log_path="systemd"

for index_volume in "${volume_index[@]}"; do
	ynh_systemctl --service="$app-volume@$index_volume" --action="stop" --log_path="systemd"
done
ynh_systemctl --service="$app-filer" --action="stop" --log_path="systemd"
ynh_systemctl --service="$app-s3" --action="stop" --log_path="systemd"

# Stop and remove workers
for index_worker in "${worker_index[@]}"; do
    ynh_systemctl --service="$app-worker@${index_worker}" --action="stop" --log_path="systemd"
    sleep 5
    yunohost service remove "$app-worker@${index_worker}"
        ynh_safe_rm /etc/systemd/system/$app-worker@${index_worker}.service
        ynh_app_setting_delete --key="$app-worker@${index_worker}" 2>/dev/null || true
        ynh_app_setting_delete --key=checksum__etc_systemd_system_$app-worker@$index_worker.service
    pushd "$install_dir"
    ynh_safe_rm worker@${index_worker}.id
    popd
done

ynh_systemctl --service="$app-admin" --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace=1

admin_secret=$(ynh_app_setting_get --app=$app --key=admin_secret)
admin_key=$(ynh_app_setting_get --app=$app --key=admin_key)
ynh_config_add --template="config.json" --destination="$install_dir/config.json"
ynh_config_add --template="security.toml" --destination="$install_dir/security.toml"

#### Recreate default worker
ynh_config_add_systemd --service="$app-worker@$next_index" --template="worker.service"

#=================================================
# CONFIG FILES
#=================================================
ynh_script_progression "Retrieving $app's configuration..."

upload_max_size=$(ynh_app_setting_get --app=$app --key=upload_max_size)

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_logrotate

touch /var/log/$app/$app-master.log
touch /var/log/$app/$app-filer.log
for index_volume in "${volume_index[@]}"; do
    touch /var/log/$app/$app-volume@$index_volume.log
done

touch /var/log/$app/$app-admin.log

chown -R $app:$app /var/log/$app/

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

yunohost service add "$app-master" --description="SeaweedFS Master" --log="/var/log/$app/$app-master.log"

for index_volume in "${volume_index[@]}"; do
	yunohost service add "$app-volume@$index_volume" --description="SeaweedFS volume@$index_volume" --log="/var/log/$app/$app-volume@${index_volume}.log"
done
yunohost service add "$app-filer" --description="SeaweedFS Filer" --log="/var/log/$app/$app-filer.log"
yunohost service add "$app-s3" --description="SeaweedFS S3 API" --log="/var/log/$app/$app-s3.log"

yunohost service add "$app-worker@$next_index" --description="SeaweedFS worker@$next_index" --log="/var/log/$app/$app-worker@${next_index}.log"

yunohost service add "$app-admin" --description="SeaweedFS Admin UI" --log="/var/log/$app/$app-admin.log"
ynh_systemctl --service="$app-master" --action="start"
for index_volume in "${volume_index[@]}"; do
	ynh_systemctl --service="$app-volume@$index_volume" --action="start"
done
ynh_systemctl --service="$app-filer" --action="start"
ynh_systemctl --service="$app-s3" --action="start"
#for index_worker in "${worker_index[@]}"; do
#	ynh_systemctl --service="$app-worker@$index_worker" --action="start"
#done

ynh_systemctl --service="$app-worker@$next_index" --action="start"
ynh_systemctl --service="$app-admin" --action="start"

sleep 30

pushd "$install_dir"
	mv worker.id "worker@${next_index}.id"
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
